version: '3.3'

services:
    proxy:
        build: ./nginx
        image: registry.gitlab.com/hub-smarthis/portal:nginx
        entrypoint: dockerize -template /app/nginx/default.temp.conf:/etc/nginx/conf.d/default.conf -wait tcp://app:8000 nginx
        environment:
            - APP_NAME=app
            - APP_PORT=8000
        networks:
            - traefik-public
            - app-network
            - database-network
            - orchestrator_bot_network
        volumes:
            - static_django:/app/static/
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.manager-http.rule=Host(`local-hub`)
                - traefik.http.routers.manager-http.entrypoints=http
                #- traefik.http.routers.manager-http.middlewares=https-redirect
                - traefik.http.routers.manager-https.rule=Host(`local-hub`)
                # - traefik.http.routers.manager-https.entrypoints=https
                # - traefik.http.routers.manager-https.tls=true
                # - traefik.http.routers.manager-https.tls.certresolver=le
                - traefik.http.services.manager.loadbalancer.server.port=80

    app:
        build: .
        image: 526932095279.dkr.ecr.us-east-1.amazonaws.com/manager:app-local
        env_file: /home/smarthis/secrets/portal/.env
        networks:
            - app-network
            - broker-network
            - database-network
            - orchestrator_bot_network
        volumes:
            - static_django:/app/static/
            - worker-volume:/app/encryption/

    worker:
        build: .
        image: 526932095279.dkr.ecr.us-east-1.amazonaws.com/manager:app-local
        entrypoint: celery -A portal worker -B -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
        env_file: /home/smarthis/secrets/portal/.env
        networks:
            - broker-network
            - orchestrator_bot_network
            - database-network
            # - bot-cpom-sp_bot-network
        volumes:
            - worker-volume:/app/encryption/

    database:
        image: postgres:14
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - database-network
        ports:
            - target: 5432
              published: 5432
              mode: host
    cache:
        image: bitnami/memcached:1.6.12-debian-10-r46
        networks:
            - app-network

networks:
    traefik-public:
        external: true
    app-network:
        attachable: true
        external: false
    broker-network:
        external: false
        attachable: true
    database-network:
        external: false
        attachable: true
    orchestrator_bot_network:
        external: true

volumes:
    static_django:
    db-data:
    worker-volume:
