# Generated by Django 3.1.1 on 2021-06-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_automationsclients_invites_usersplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersplans',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.client'),
        ),
    ]
