# Generated by Django 3.1.1 on 2021-06-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(default='RH', max_length=100),
        ),
    ]
