# Generated by Django 3.1.1 on 2021-07-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20210705_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default='RH', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='begin',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end',
            field=models.DateField(auto_now=True),
        ),
    ]
