# Generated by Django 3.1.1 on 2021-09-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_sessioninfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioninfo',
            name='user',
        ),
        migrations.AddField(
            model_name='sessioninfo',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
