# Generated by Django 3.1.1 on 2021-09-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_auto_20210917_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cnpj',
            field=models.CharField(default='Not provided', max_length=14),
        ),
        migrations.AddField(
            model_name='plan',
            name='qnt_queries',
            field=models.IntegerField(default=0),
        ),
    ]
