# Generated by Django 3.1.1 on 2021-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_auto_20210923_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='qnt_extra_queries',
            field=models.IntegerField(default=0),
        ),
    ]
