# Generated by Django 3.1.1 on 2021-10-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_auto_20210930_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
