# Generated by Django 3.1.1 on 2021-10-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20211008_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagarmePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_pagarme_id', models.CharField(max_length=200)),
                ('plan_pagarme_name', models.CharField(max_length=200)),
                ('is_test', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Service Account'), (2, 'Client'), (3, 'Admin'), (4, 'Main'), (5, 'Editor Account'), (6, 'View Account')], default=1),
        ),
        migrations.CreateModel(
            name='PagarmeSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_pagarme_id', models.CharField(max_length=200)),
                ('plan_pagarme_id', models.CharField(max_length=200)),
                ('is_test', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.client')),
            ],
        ),
    ]
