# Generated by Django 3.1.1 on 2021-10-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20211008_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='Not provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Service Account'), (2, 'Client'), (3, 'Admin'), (4, 'Main'), (5, 'Editor Account'), (6, 'View Account')], default=1),
        ),
    ]
