# Generated by Django 3.1.1 on 2021-11-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_auto_20211018_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(default='Not provided', max_length=14, unique=True)),
                ('razao_social', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.AlterModelOptions(
            name='automationsclients',
            options={'verbose_name_plural': 'Automation clients'},
        ),
        migrations.AlterModelOptions(
            name='invites',
            options={'verbose_name_plural': 'Invites'},
        ),
        migrations.AlterModelOptions(
            name='usersplans',
            options={'verbose_name_plural': 'User plans'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.companies'),
        ),
    ]
