# Generated by Django 3.1.1 on 2021-10-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_auto_20211018_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagarmePlan',
            new_name='PagarmePlans',
        ),
        migrations.RenameModel(
            old_name='PagarmeSignature',
            new_name='PagarmeSignatures',
        ),
    ]
