# Generated by Django 3.1.1 on 2021-11-10 12:58

from django.db import migrations, models
import subscriptions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_auto_20211109_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[subscriptions.validators.validate_cnpj_when_created]),
        ),
    ]
