# Generated by Django 3.1.1 on 2021-10-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_auto_20211018_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagarmeSignatures',
            new_name='PagarmeSubscriptions',
        ),
    ]
