# Generated by Django 3.1.1 on 2021-10-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_auto_20211018_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagarmesubscriptions',
            old_name='signature_pagarme_id',
            new_name='subscription_pagarme_id',
        ),
    ]
