# Generated by Django 3.1.1 on 2021-11-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_auto_20211110_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.client'),
        ),
    ]
