# Generated by Django 3.1.1 on 2021-10-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_auto_20211018_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarmeplans',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=149, max_digits=15),
        ),
    ]
