# Generated by Django 3.1.1 on 2021-10-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_auto_20211018_1916'),
        ('subscriptions', '0020_pagarmeplans_amount'),
    ]

    operations = [
    ]
