# Generated by Django 3.1.13 on 2021-11-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0021_merge_20211028_1924'),
        ('subscriptions', '0019_invites_client'),
    ]

    operations = [
    ]
