# Generated by Django 3.1.13 on 2021-11-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_merge_20211122_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarmeplans',
            name='api_version',
            field=models.CharField(default='v4', max_length=10),
        ),
        migrations.AddField(
            model_name='pagarmesubscriptions',
            name='api_version',
            field=models.CharField(default='v4', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagarmeplans',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=14900, max_digits=15),
        ),
    ]
