# Generated by Django 3.1.13 on 2021-11-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_auto_20211122_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarmeplans',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pagarmesubscriptions',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
