# Generated by Django 3.1.13 on 2021-11-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_auto_20211122_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagarmeplans',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagarmesubscriptions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
