# Generated by Django 3.2.9 on 2021-12-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_auto_20211122_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_period',
            field=models.PositiveSmallIntegerField(default=14),
        ),
    ]
