# Generated by Django 3.2.10 on 2021-12-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0026_subscription_trial_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninfo',
            name='user_ip_address',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
    ]
