# Generated by Django 3.2.10 on 2022-01-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0027_profile_email_confirmed'),
        ('subscriptions', '0027_sessioninfo_user_ip_address'),
    ]

    operations = [
    ]
