# Generated by Django 3.2.10 on 2022-01-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0028_merge_20220103_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_period',
            field=models.SmallIntegerField(default=14),
        ),
    ]
