# Generated by Django 3.2.10 on 2022-01-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0028_auto_20220103_1921'),
        ('subscriptions', '0029_auto_20220117_2107'),
    ]

    operations = [
    ]
