# Generated by Django 3.2.10 on 2022-02-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0030_merge_0028_auto_20220103_1921_0029_auto_20220117_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarmesubscriptions',
            name='begin',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pagarmesubscriptions',
            name='end',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
