# Generated by Django 3.2.10 on 2022-02-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0031_auto_20220209_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagarmesubscriptions',
            old_name='end',
            new_name='current_period_end',
        ),
        migrations.RenameField(
            model_name='pagarmesubscriptions',
            old_name='begin',
            new_name='current_period_start',
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(default='trialing', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='begin',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
