# Generated by Django 3.2.10 on 2022-02-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0032_auto_20220217_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagarmeplans',
            options={'verbose_name_plural': 'PagarmePlans'},
        ),
        migrations.AlterModelOptions(
            name='pagarmesubscriptions',
            options={'verbose_name_plural': 'PagarmeSubscriptions'},
        ),
    ]
