# Generated by Django 3.2.10 on 2022-02-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0033_auto_20220221_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='begin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
