# Generated by Django 3.2.10 on 2022-02-22 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0035_alter_subscription_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarmesubscriptions',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('boleto', 'Boleto')], default='credit_card', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='begin',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
