# Generated by Django 3.2.10 on 2022-02-24 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0036_auto_20220222_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='begin',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
