# Generated by Django 3.2.10 on 2022-03-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0037_alter_subscription_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsclients',
            name='can_create_model',
            field=models.BooleanField(default=True),
        ),
    ]
