# Generated by Django 3.2.10 on 2022-03-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0038_automationsclients_can_create_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationsclients',
            name='can_create_model',
        ),
    ]
