# Generated by Django 3.2.10 on 2022-03-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0039_remove_automationsclients_can_create_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsclients',
            name='can_create_model',
            field=models.PositiveSmallIntegerField(choices=[(1, 'LIBERADO'), (2, 'AGUARDANDO'), (3, 'NÃO-LIBERADO')], default=1),
        ),
    ]
