# Generated by Django 3.2.13 on 2022-07-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0042_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='logo_path',
        ),
        migrations.AddField(
            model_name='client',
            name='domain',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
