# Generated by Django 3.2.13 on 2022-07-06 17:55

from django.db import migrations
import uuid


def fill_client_domain_and_identifier(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Client = apps.get_model('subscriptions', 'Client')
    User = apps.get_model('subscriptions', 'User')
    identifiers = []
    for client in Client.objects.all().order_by('id'):
        standard_emails = ['gmail', 'yahoo', 'hotmail',
                           'aol', 'live', 'outlook', 'protonmail', 'dukeoo', 'icloud']
        first_user = User.objects.filter(profile__client=client).first()

        if not first_user:
            client.domain = '-'
            unique_identifier = str(uuid.uuid4())
            client.identifier = unique_identifier
            client.save()
            continue

        user_email = first_user.email
        user_domain = user_email.split('@')[-1]

        is_standard_email = False
        for email in standard_emails:
            if email in user_email:
                is_standard_email = True

        client.domain = user_domain

        if is_standard_email:
            unique_identifier = str(uuid.uuid4())
            client.identifier = unique_identifier
        else:
            if user_domain in identifiers:
                count = 1
                while f"{user_domain}-{count}" in identifiers:
                    count += 1
                new_identifier = f"{user_domain}-{count}"

                client.identifier = new_identifier
                identifiers.append(new_identifier)
            else:
                client.identifier = user_domain
                identifiers.append(user_domain)

        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0043_auto_20220706_1754'),
    ]

    operations = [
        migrations.RunPython(fill_client_domain_and_identifier),
    ]
