# Generated by Django 3.2.13 on 2022-07-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0044_auto_20220706_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
