# Generated by Django 3.1.1 on 2021-06-22 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo_path', models.URLField(blank=True, max_length=150, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('public_key', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('input_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_format', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'IDDLE'), (2, 'RUNNING'), (3, 'FAULTED')], default=1)),
                ('email_to_send_results', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smt_orchestrator.automation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'automation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'IDDLE'), (2, 'READY'), (3, 'PROCESSING'), (4, 'FAULTED'), (5, 'CANCELED'), (6, 'FINISHED')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smt_orchestrator.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleExtraInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_info', models.CharField(blank=True, max_length=300, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smt_orchestrator.schedule')),
            ],
        ),
    ]
