# Generated by Django 3.1.1 on 2021-08-11 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smt_orchestrator', '0003_futureautomation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureautomation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
