# Generated by Django 3.1.1 on 2021-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0004_auto_20210811_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
