# Generated by Django 3.1.1 on 2021-11-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0006_interestedinserviceundermaintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
