# Generated by Django 3.1.1 on 2021-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0007_captchausage'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchausage',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
