# Generated by Django 3.1.1 on 2021-11-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0008_captchausage_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captchausage',
            old_name='value',
            new_name='saldo',
        ),
    ]
