# Generated by Django 3.1.1 on 2021-11-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0009_auto_20211105_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchausage',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='captchausage',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
