# Generated by Django 3.1.13 on 2021-11-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0010_auto_20211105_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchausage',
            name='engine',
            field=models.CharField(blank=True, default='Not provided', max_length=300, null=True),
        ),
    ]
