# Generated by Django 3.2.9 on 2021-12-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0011_captchausage_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'IDDLE'), (2, 'READY'), (3, 'PROCESSING'), (4, 'FAULTED'), (5, 'CANCELED'), (6, 'FINISHED'), (7, 'RESULTS SENT')], default=1),
        ),
    ]
