# Generated by Django 3.2.9 on 2021-12-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0012_alter_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number_of_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='number_of_successfull_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(default='FRONT', max_length=300),
        ),
    ]
