# Generated by Django 3.2.10 on 2022-02-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0013_auto_20211223_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
