# Generated by Django 3.2.10 on 2022-02-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0014_schedule_is_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_scheduled',
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurrence',
            field=models.PositiveSmallIntegerField(choices=[(0, 'WITHOUT-REPEAT'), (30, 'MONTHLY'), (7, 'WEEKLY')], default=0),
        ),
    ]
