# Generated by Django 3.2.10 on 2022-02-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0015_auto_20220210_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='execution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
