# Generated by Django 3.2.10 on 2022-02-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0031_auto_20220209_1609'),
        ('smt_orchestrator', '0016_schedule_execution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='client',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.client'),
        ),
    ]
