# Generated by Django 3.2.10 on 2022-02-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0019_schedule_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='is_showcase',
            field=models.BooleanField(default=False),
        ),
    ]
