# Generated by Django 3.2.10 on 2022-04-28 18:45

from django.db import migrations

from django.db import connection

def create_orchestrator_database_input(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            "CREATE TABLE public.smt_orchestrator_input_line (\
            id serial NOT NULL,\
            line_number int4 NOT NULL,\
            line_data json NOT NULL,\
            schedule_id int4 NOT NULL,\
            CONSTRAINT smt_orchestrator_input_line_pk PRIMARY KEY (id));\
            ")
        cursor.execute("ALTER TABLE public.smt_orchestrator_schedule ADD credentials json NULL;")


def destroy_orchestrator_database_input(apps, schema_editor):  # pragma: no cover
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE public.smt_orchestrator_input_line;")
        cursor.execute("ALTER TABLE public.smt_orchestrator_schedule DROP COLUMN credentials;")

class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0020_automation_is_showcase'),
    ]

    operations = [
        migrations.RunPython(create_orchestrator_database_input, destroy_orchestrator_database_input),
    ]
