# Generated by Django 3.2.10 on 2022-04-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0020_automation_is_showcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='execution_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='schedule',
            name='cron_expression',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='SchedulesAppointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateTimeField(auto_now=True)),
                ('recurrence', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'WITHOUT-REPEAT'), (30, 'MONTHLY'), (7, 'WEEKLY')], default=0, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smt_orchestrator.schedule')),
            ],
        ),
    ]
