# Generated by Django 3.2.10 on 2022-04-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0021_auto_20220406_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='execution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurrence',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'WITHOUT-REPEAT'), (30, 'MONTHLY'), (7, 'WEEKLY')], default=0, null=True),
        ),
    ]
