# Generated by Django 3.2.10 on 2022-04-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0022_auto_20220407_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='execution_date',
        ),
    ]
