# Generated by Django 3.2.10 on 2022-04-29 21:07

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0023_remove_schedule_execution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='execution_date',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True),
        ),
    ]
