# Generated by Django 3.2.13 on 2022-05-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0021_auto_20220428_1845'),
        ('smt_orchestrator', '0025_delete_schedulesappointments'),
    ]

    operations = [
    ]
