# Generated by Django 3.2.13 on 2022-05-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0026_merge_20220520_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='output_files_in_pdf',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
