# Generated by Django 3.2.13 on 2022-06-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0027_schedule_output_files_in_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='url',
        ),
        migrations.AddField(
            model_name='automation',
            name='display_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='display_name_es',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='display_name_pt_br',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='group',
            field=models.CharField(choices=[('banking', 'Banking'), ('cadastral_status', 'Cadastral Status'), ('cars_and_transit', 'Cars/Transit'), ('consumption_accounts', 'Consumption Accounts'), ('criminal_record', 'Criminal Record'), ('debt_certificates', 'Debt Certificates'), ('international', 'International'), ('management', 'Management'), ('nfe_and_nfse', 'NF-e / NFS-e'), ('processes', 'Processes'), ('taxes', 'Taxes')], default='management', max_length=150),
        ),
        migrations.AddField(
            model_name='automation',
            name='type',
            field=models.CharField(choices=[('upload', 'Upload'), ('credential', 'Credential'), ('upload_and_credential', 'Upload and Credential'), ('credential_and_filter_notes', 'Credential and Filter Notes')], default='upload', max_length=150),
        ),
    ]
