# Generated by Django 3.2.13 on 2022-07-01 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0042_alter_profile_phone'),
        ('smt_orchestrator', '0028_auto_20220630_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.client'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='display_name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='display_name_es',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='display_name_pt_br',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
