# Generated by Django 3.2.13 on 2022-07-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0031_task_scheduled_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICMSVivara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, null=True)),
                ('num_capta', models.CharField(max_length=255, null=True)),
                ('store', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('uf', models.CharField(max_length=255, null=True)),
                ('cep', models.CharField(max_length=255, null=True)),
                ('cnpj', models.CharField(max_length=255, null=True)),
                ('insc_estadual', models.CharField(max_length=255, null=True)),
                ('insc_municipal', models.CharField(max_length=255, null=True)),
                ('responsible', models.CharField(max_length=255, null=True)),
                ('receipt_code_icms', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'smt_orchestrator_icms_vivara',
            },
        ),
        migrations.CreateModel(
            name='ICMSVivaraConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=255, null=True, unique=True)),
                ('qualification', models.CharField(max_length=255, null=True)),
                ('expiration', models.CharField(max_length=255, null=True)),
                ('icms_rule', models.CharField(max_length=255, null=True)),
                ('receita_code', models.CharField(max_length=255, null=True)),
                ('tipo_debito', models.CharField(max_length=255, null=True)),
                ('codigo_operacao', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'smt_orchestrator_icms_vivara_config',
            },
        ),
        migrations.CreateModel(
            name='ICMSVivaraRJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=255, null=True)),
                ('qualification', models.CharField(max_length=255, null=True)),
                ('reference_period', models.DateField(null=True)),
                ('informed_icms', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('informed_fecp', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
            ],
            options={
                'db_table': 'smt_orchestrator_icms_vivara_rj',
            },
        ),
    ]
