# Generated by Django 3.2.13 on 2022-07-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_orchestrator', '0032_icmsvivara_icmsvivaraconfig_icmsvivararj'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchausage',
            name='from_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
