# Generated by Django 3.1.1 on 2021-09-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSessionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField()),
                ('session_duration', models.TimeField()),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
