# Generated by Django 3.1.1 on 2021-06-22 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0002_automationsclients_invites_usersplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.client')),
            ],
            options={
                'verbose_name': 'Areas log',
                'verbose_name_plural': 'Areas logs',
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=150)),
                ('auto_update', models.BooleanField(default=False)),
                ('orchestrator_url', models.CharField(blank=True, max_length=150, null=True)),
                ('tenant_name', models.CharField(blank=True, max_length=150, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=150, null=True)),
                ('client_id', models.CharField(blank=True, max_length=150, null=True)),
                ('last_update', models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=utc))),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.client')),
            ],
        ),
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(blank=True, max_length=150, null=True)),
                ('duration_time', models.FloatField(blank=True, null=True)),
                ('ReleaseName', models.CharField(blank=True, max_length=150, null=True)),
                ('salary_collaborator', models.FloatField(blank=True, null=True)),
                ('hours_collaborator', models.IntegerField(blank=True, null=True)),
                ('howmany_collaborators', models.IntegerField(blank=True, null=True)),
                ('project_cost', models.FloatField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uipath_logs.areas')),
            ],
            options={
                'verbose_name': 'Processos log',
                'verbose_name_plural': 'Processoss logs',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('Key', models.SlugField(max_length=36, primary_key=True, serialize=False)),
                ('Id', models.IntegerField(blank=True, null=True)),
                ('ReleaseVersionId', models.IntegerField(blank=True, null=True)),
                ('StartingScheduleId', models.IntegerField(blank=True, null=True)),
                ('StartTime', models.DateTimeField(blank=True, null=True)),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
                ('CreationTime', models.DateTimeField(blank=True, null=True)),
                ('State', models.CharField(blank=True, max_length=150, null=True)),
                ('Source', models.CharField(blank=True, max_length=150, null=True)),
                ('SourceType', models.CharField(blank=True, max_length=150, null=True)),
                ('BatchExecutionKey', models.CharField(blank=True, max_length=150, null=True)),
                ('Info', models.TextField(blank=True, null=True)),
                ('ReleaseName', models.CharField(blank=True, max_length=150, null=True)),
                ('Type', models.CharField(blank=True, max_length=150, null=True)),
                ('OutputArguments', models.TextField(blank=True, null=True)),
                ('HostMachineName', models.CharField(blank=True, max_length=150, null=True)),
                ('HasMediaRecorded', models.BooleanField(blank=True, default=False, null=True)),
                ('InputArguments', models.TextField(blank=True, null=True)),
                ('PersistenceId', models.CharField(blank=True, max_length=150, null=True)),
                ('ResumeVersion', models.CharField(blank=True, max_length=150, null=True)),
                ('StopStrategy', models.CharField(blank=True, max_length=150, null=True)),
                ('Context', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uipath_logs.context')),
            ],
            options={
                'verbose_name': 'Job log',
                'verbose_name_plural': 'Jobs logs',
            },
        ),
    ]
