# Generated by Django 3.1.1 on 2021-10-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20210706_1827'),
        ('uipath_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.client'),
        ),
    ]
