# Generated by Django 3.2.10 on 2022-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uipath_logs', '0002_processos_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='average_single_transaction_time',
            field=models.FloatField(default=0),
        ),
    ]
