# Generated by Django 3.2.10 on 2022-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uipath_logs', '0003_alter_job_releasename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='ReleaseName',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
