# Generated by Django 3.2.10 on 2022-02-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uipath_logs', '0003_processos_average_single_transaction_time'),
        ('uipath_logs', '0004_alter_processos_releasename'),
    ]

    operations = [
    ]
