# Generated by Django 3.2.10 on 2022-03-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uipath_logs', '0006_auto_20220217_1858'),
        ('uipath_logs', '0006_auto_20220224_2209'),
    ]

    operations = [
    ]
