# Generated by Django 3.2.10 on 2022-04-08 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uipath_logs', '0008_uipathprocessesschedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='average_single_transaction_time',
        ),
        migrations.AddField(
            model_name='processos',
            name='name',
            field=models.CharField(default='Not provided', max_length=150),
        ),
        migrations.CreateModel(
            name='SubProcessos',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ReleaseName', models.CharField(blank=True,
                 db_index=True, max_length=150, null=True)),
                ('average_single_transaction_time',
                 models.FloatField(blank=True, null=True)),
                ('process', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='uipath_logs.processos')),
            ],
        ),
    ]
