# Generated by Django 3.2.10 on 2022-05-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uipath_logs', '0009_auto_20220408_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprocessos',
            name='average_single_transaction_time',
        ),
    ]
