# Generated by Django 3.2.13 on 2022-05-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uipath_logs', '0010_remove_subprocessos_average_single_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='average_hour_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='processos',
            name='quantity_of_monthly_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
