# Generated by Django 3.2.13 on 2022-07-26 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0045_alter_client_identifier'),
        ('uipath_logs', '0011_auto_20220530_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='UipathApiMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.CharField(blank=True, max_length=300, null=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.client')),
            ],
        ),
    ]
