from django.urls import path
from . import views
from django.conf.urls import include

urlpatterns = [
    path('get/upload/presigned-url', views.get_upload_presigned_url,
         name='get_upload_presigned_url'),
    path('', views.onboarding_user, name='onboarding'),
    path('services', views.services, name='services'),
    path('services/tab/<str:active_tab>', views.services, name='services'),
    path('services/singletab/<str:tab>',
         views.services_singletab, name='services_singletab'),
    path('services/search',
         views.services, name='services_search_results'),
    path('services/<str:automation_name>',
         views.automations, name='automations'),
    path('services/model/new', views.create_new_model, name='new_model'),
    path('services/model/edit/<int:model_id>',
         views.edit_existing_model, name='edit_model'),
    path('services/model/remove/<int:model_id>',
         views.remove_model, name='remove_model'),
    path('services/automation/cancel/<int:schedule_id>',
         views.cancel_automation, name='cancel_automation'),
    path('services/automation/start/<int:schedule_id>',
         views.start_automation, name='start_automation'),
    path('services/automation/stop/<int:schedule_id>',
         views.stop_automation, name='stop_automation'),
    path('services/check/file',
         views.check_upload_file, name='check_upload_file'),
    path('services/check/model/',
         views.check_running_model_state, name='check_running_model_state'),
    path('services/manage/permissions', views.manage_client_permissions,
         name='manage_client_permissions'),
    path('services/delete/permissions', views.delete_client_permissions,
         name='delete_client_permissions'),
    path('discover', views.discover, name='discover'),
    path('discover/search',
         views.discover, name='discover_search_results'),
    path('discover/add', views.save_single_service_to_database,
         name='discover_add_service'),
    path('discover/future_service',
         views.register_for_future_service, name='future_service'),
    path('discover/interested_maintenance',
         views.interested_in_service_under_maintenance, name='interested-maintenance'),
    path('discover/services-info/<str:automation_name>',
         views.get_switch_services_modal, name='get_switch_services_modal'),
    path('discover/<str:automation_name>',
         views.discover_service, name='discover_service'),
    #     path('api-hub', views.api_hub, name='api_hub'),
    #     path('api-hub/request/email', views.api_hub_request_email,
    #          name='api_hub_request_email'),
    path('schedules/appointment',
         views.appointment, name='appointment'),
    path('schedules/appointment/<int:id>',
         views.delete_appointment, name='delete_appointment'),
    path('services/request-modal-creation/<str:automation_name>',
         views.request_modal_creation, name='request_modal_creation'),
    path('dashboard-automation',
         views.get_dashboard_automations_info, name='dashboard_automation'),
    path('monitor/executions',
         views.get_executions_monitoring_info, name='monitoring_executions'),


]
